### ISSUE TITLE
Can't get working with Leaflet 1.3.3

### ISSUE THREAD

**Issue by humblecoder** [iatkin/leaflet-svgicon#12]
Full disclosure.  I've been using Leaflet with VueJS for a while now.  Currently using 1.3.3 and all works well with default markers, etc.  However, I attempted to include this library and I'm now receiving

```TypeError: this.callInitHooks is not a function```

when I use it.  I'm certain it's a mistake on my part, but I have no idea what the issue is.

**Comment by humblecoder** [comment]
Hrm, just saw [this issue](https://stackoverflow.com/questions/40598594/import-and-use-untyped-leaflet-js-plugin-with-typescript-2-in-angular-2-project).  I'm guessing this needs to be updated to support later versions?

**Comment by iatkin** [comment]
Hi. I poked around and this issue occurs if the code that uses the marker class is located in the head element. It's fine if the code is in the body element for some reason. A previous version of this comment misstated the exact issue and workaround.

**Comment by iatkin** [comment]
Ugh, sorry for the multiple comments and edits. I've tried reproducing this multiple times, and was only able to once. It now works without issue like normal. As I mentioned above, sticking the code in the body element fixed the issue originally. I'm going to close this issue as the code itself is fine. Feel free to create a new issue if you are still having problem along with some sample code.
